---
apiVersion: v1
kind: Service
metadata:
  name: threepilar-example-service
  namespace: ns1
spec:
  selector:
    app: threepilar-example
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: threepilar-example-route
  namespace: ns1
spec:
  to:
    kind: Service
    name: threepilar-example-service
    weight: 100
  port:
    targetPort: 8090
